services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: npm start
    restart: unless-stopped
    networks:
      - playwright-network

  playwright:
    build: .
    stdin_open: true      # Keep STDIN open for interactive use (-i flag)
    tty: true             # Allocate pseudo-TTY for terminal (-t flag)
    volumes:
      - ./test-history:/app/test-history  # Persist test results to host
      - ./test-domains.sh:/app/test-domains.sh  # Mount sequential test script
      - ./test-domains-parallel.sh:/app/test-domains-parallel.sh  # Mount parallel test script
      - ./tests:/app/tests  # Mount entire tests directory for updated test files
      - ./playwright.config.js:/app/playwright.config.js  # Mount config
    environment:
      - TEST_URL=${TEST_URL:-https://www.uchicago.edu/}
    working_dir: /app
    depends_on:
      - app
    networks:
      - playwright-network

networks:
  playwright-network:
    driver: bridge
